# Write your MySQL query statement below
WITH T1 AS ( 
    SELECT SUBSTRING(CONVERT(TRANS_DATE ,CHAR),1,7) AS MONTH, COUNTRY AS COUNTRY , SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,COUNT(STATE) AS TRANS_COUNT  FROM TRANSACTIONS GROUP BY MONTH,COUNTRY
),T2 AS (
    SELECT SUBSTRING(CONVERT(TRANS_DATE ,CHAR),1,7) AS MONTH, COUNTRY AS COUNTRY , SUM(AMOUNT) AS APPROVED_TOTAL_AMOUNT,COUNT(STATE) AS APPROVED_COUNT  FROM TRANSACTIONS WHERE STATE ='approved' GROUP BY MONTH,COUNTRY 
)
SELECT T1.MONTH AS MONTH,T1.COUNTRY AS COUNTRY,T1.TRANS_COUNT AS TRANS_COUNT ,IFNULL(T2.APPROVED_COUNT,0) AS APPROVED_COUNT ,T1.TRANS_TOTAL_AMOUNT AS TRANS_TOTAL_AMOUNT,IFNULL(T2.APPROVED_TOTAL_AMOUNT,0) AS APPROVED_TOTAL_AMOUNT FROM T1 LEFT JOIN T2 ON IFNULL(T1.MONTH,"NULL") =IFNULL(T2.MONTH,"NULL") AND IFNULL(T1.COUNTRY,"NULL") =  IFNULL(T2.COUNTRY,"NULL");



# SELECT SUBSTRING(CONVERT(TRANS_DATE ,CHAR),1,7) AS MONTH, COUNTRY AS COUNTRY , SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,COUNT(STATE) AS TRANS_COUNT  FROM TRANSACTIONS GROUP BY MONTH,COUNTRY;

# SELECT SUBSTRING(CONVERT(TRANS_DATE ,CHAR),1,7) AS MONTH, COUNTRY AS COUNTRY , SUM(AMOUNT) AS APPROVED_TOTAL_AMOUNT,COUNT(STATE) AS APPROVED_COUNT  FROM TRANSACTIONS WHERE STATE ='approved' GROUP BY MONTH,COUNTRY




