# Write your MySQL query statement below
WITH T1 AS (
    SELECT DELIVERY_ID, CUSTOMER_ID ,CUSTOMER_PREF_DELIVERY_DATE,ORDER_DATE, MIN(ORDER_DATE) OVER (PARTITION BY CUSTOMER_ID) AS FIRST_ORDER_DATE FROM DELIVERY
),T2 AS (
    SELECT COUNT(*) AS TOTAL_CUSTOMER FROM T1 WHERE FIRST_ORDER_DATE = ORDER_DATE
),T3 AS (
    SELECT COUNT(*) AS LUCKY_CUSTOMER FROM T1 WHERE FIRST_ORDER_DATE = ORDER_DATE AND FIRST_ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE
)SELECT ROUND((LUCKY_CUSTOMER/TOTAL_CUSTOMER)*100,2) AS IMMEDIATE_PERCENTAGE FROM T2 JOIN T3 ;